//@flow
export const NEW_CONTACT_FORM_VISIBILITY = 'NEW_CONTACT_FORM_VISIBILITY';
export const DID_ADD_CONTACT = "DID_ADD_CONTACT";
export const DID_FETCH_NEW_CONTACT = "DID_FETCH_NEW_CONTACT";
export const DID_FETCH_CONTACTS = "DID_FETCH_CONTACTS";
export const CHANGE_CURRENT_CONTACT = "CHANGE_CURRENT_CONTACT";
export const DID_DELETE_CONTACT = "DID_DELETE_CONTACT";
export const DID_GET_GOGGLE_AUTH_URL = "DID_GET_GOGGLE_AUTH_URL";
export const DID_CREATE_USER = "DID_CREATE_USER";

//export const USER_JOIN = "USER_JOIN";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SET_SIGNUP_ERROR = "SET_SIGNUP_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const REFRESH_SESSION_SUCCESS = "REFRESH_SESSION_SUCCESS";
export const REFRESH_SESSION_ERROR = "REFRESH_SESSION_ERROR";
export const CLEAR_APP_MESSAGE = "CLEAR_APP_MESSAGE";
export const RESET_APP = 'RESET_APP';

export const SAVE_PROFILE_DETAILS_SUCCESS = "SAVE_PROFILE_DETAILS_SUCCESS";
export const GET_CURRENT_CONTACT_DETAILS_SUCCESS = "GET_CURRENT_CONTACT_DETAILS_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const POP_MESSAGE_SUCCESS = "POP_MESSAGE_SUCCESS";


export const SET_PAGE = "SET_PAGE";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SEARCH_CONTACTS_SUCCESS = "SEARCH_CONTACTS_SUCCESS";
export const REQUEST_CONTACT_SUCCESS = "REQUEST_CONTACT_SUCCESS";
export const LOAD_ADDRESS_BOOK_SUCCESS = "LOAD_ADDRESS_BOOK_SUCCESS";
export const GET_CONTACT_FOR_VIEW_SUCCESS = "GET_CONTACT_FOR_VIEW_SUCCESS";

export const LOAD_PREFIX_TYPES_SUCCESS = "LOAD_PREFIX_TYPES_SUCCESS";
export const LOAD_SUFFIX_TYPES_SUCCESS = "LOAD_SUFFIX_TYPES_SUCCESS";
export const LOAD_PHONE_TYPES_SUCCESS = "LOAD_PHONE_TYPES_SUCCESS";
export const LOAD_EMAIL_TYPES_SUCCESS = "LOAD_EMAIL_TYPES_SUCCESS";
export const LOAD_ADDRESS_TYPES_SUCCESS = "LOAD_ADDRESS_TYPES_SUCCESS";
export const LOAD_STATES_OF_US_SUCCESS = "LOAD_STATES_OF_US_SUCCESS";
